# Generated by Django 3.2.5 on 2021-09-05 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_item_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('same_billing_address', models.BooleanField()),
                ('save_info', models.BooleanField()),
                ('payment_option', models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
