# Generated by Django 3.2.5 on 2021-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210905_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
