# Generated by Django 3.2.5 on 2021-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211008_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.CharField(max_length=100),
        ),
    ]
